# Generated by Django 5.2 on 2025-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='vote',
            field=models.SmallIntegerField(),
        ),
    ]
